---

- name: Setup Raspberry Pi's For Mpich3 Install
  hosts: all
  gather_facts: no
  vars:
    packages_to_install: [cockpit, gfortran, wget, python3, python3-dev, python3-pip, vim, python-dev, python-setuptools]
    pip_packages: [mpi4py]
  become: yes

  tasks:
    - name: Update Pi's
      apt: upgrade=dist force_apt_get=yes

    - name: Install Packages
      apt: pkg={{ packages_to_install }} state=present update_cache=yes
    
    - name: Install mpi4py
      pip:
        name: mpi4py
        executable: pip3

    - name: Add folder for auto rsync of scripts to all hosts
      file:
        path: /home/pi/scripts
        state: directory
        mode: '0755'

    - name: Enable Cockpit for cluster monitoring
      systemd:
        name: cockpit
        state: started
        enabled: yes
   